PILOT-1280: Clean up config file
PilotDataPlatform/pipelines pull request #18
Opened 2022-07-18 17:48 UTC by QXgu

## Summary

PILOT-1280: Clean up config file 

## JIRA Issues

https://indocconsortium.atlassian.net/browse/PILOT-1280

## Type of Change

Please delete options that are not relevant.

- [ ] Refactor or reformatting

## Testing

Are there any new or updated tests to validate the changes?

- [ ] Yes
- [ ] No

## Test Directions

(Additional instructions for how to run tests or validate functionality if not covered by unit tests)

2022-07-19 11:49 UTC, vmoshynskyi requested changes
Please take a look at my comments.

2022-07-19 11:49 UTC, vmoshynskyi commented on .pre-commit-config.yaml
> +            '--max-line-length=150',
I don't think it's a good idea to change this only in one project.
Either we discuss and change this every where or we stick with once rule for all repos.

2022-07-19 11:49 UTC, vmoshynskyi commented on filecopy/operations/config.py
>      PROVENANCE_SERVICE: str
This service has need renamed into `AUDIT_TRAIL_SERVICE`.
Please update usage and also in `.env.schema` files.

2022-07-19 11:49 UTC, vmoshynskyi commented on filecopy/operations/config.py
>      CATALOGUING_SERVICE: str
Also please change this one into `LINEAGE_SERVICE`.

2022-07-19 11:49 UTC, vmoshynskyi commented on filecopy/operations/commands/copy.py
> +    MINIO_URL = f'{settings.MINIO_HOST}:{settings.MINIO_PORT}'
Please move these all vars into the `Settings` object.
The point of the `Settings` object is that all necessary vars or var transformations/concatenations happen in one place.
It's better to have `REDIS_URL` and `MINIO_URL` in one object, rather than duplicated in different files.

2022-07-19 11:49 UTC, vmoshynskyi commented on filecopy/operations/commands/copy.py
> +            DB_URI = f'postgresql://{settings.RDS_USER}:{settings.RDS_PWD}@{settings.RDS_HOST}:{settings.RDS_PORT}/{settings.RDS_DBNAME}'
This also should be in `Settings`.

2022-07-19 11:49 UTC, vmoshynskyi commented on bids-validator/scripts/database_service.py
> +SQL_URL = f'postgresql://{ConfigClass.RDS_USER}:{ConfigClass.RDS_PWD}@{ConfigClass.RDS_HOST}:{ConfigClass.RDS_PORT}/{ConfigClass.DATASET_RDS_DBNAME}'
Please move this into `Settings` as well.
It's better to name it `DATASET_RDS_URL`.

2022-07-19 19:18 UTC, QXgu commented on bids-validator/scripts/database_service.py
> +SQL_URL = f'postgresql://{ConfigClass.RDS_USER}:{ConfigClass.RDS_PWD}@{ConfigClass.RDS_HOST}:{ConfigClass.RDS_PORT}/{ConfigClass.DATASET_RDS_DBNAME}'
All the fix is up, I pushed the PILOT-1321(another task) accidentally. But it seems all the fix is up on this branch after merging. Please took a look. Thanks!

2022-07-20 17:26 UTC, vmoshynskyi requested changes
Please check my comments.

2022-07-20 18:02 UTC, QXgu commented on filecopy/operations/config.py
> +    MINIO_URL: str = ''
@vmoshynskyi All the fix is up, please take a look

2022-07-20 18:47 UTC, vmoshynskyi approved these changes
Thank you for the corrections.

2022-07-20 19:11 UTC, merged