Pilot 1693: Refactory copy request in pipelines service and deprecate the connection to approval db in copy pipeline
PilotDataPlatform/pipelines pull request #33
Opened 2022-09-29 15:17 UTC by QXgu

## Summary

 Refactory copy request in pipelines service and deprecate the connection to approval db in copy pipeline

## JIRA Issues

https://indocconsortium.atlassian.net/browse/PILOT-1693
https://indocconsortium.atlassian.net/browse/PILOT-1694

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Refactor or reformatting

## Testing

Are there any new or updated tests to validate the changes?

- [ ] Yes
- [ ] No

## Test Directions

(Additional instructions for how to run tests or validate functionality if not covered by unit tests)

2022-10-13 16:24 UTC, vmoshynskyi requested changes
Please check my comments.

2022-10-13 16:24 UTC, vmoshynskyi commented on filecopy/operations/services/approval/client.py
> +            raise Exception(f'Unable to update copy status for {entity_id}')
Based on our discussion I would suggest to have here:
```suggestion
        if response.status_code == 200 and len(response.json()['result']) == 0:
            raise Exception(f'Unable to update copy status for {entity_id}, entity is not found.')
        if response.status_code != 200:
            raise Exception(f'Unable to update copy status for {entity_id}')
```
Because if we have `status_code != 200` this mean that response might have unexpected structure and `result` field might be missing, so we should trust response only if we have 200 status code.

2022-10-13 16:24 UTC, vmoshynskyi commented on filecopy/operations/managers.py
> +        approved_entities: List[str],
```suggestion
        approved_entities: List[UUID],
```

2022-10-13 16:24 UTC, vmoshynskyi commented on filecopy/operations/managers.py
> +        approved_entities: Optional[list],
```suggestion
        approved_entities: Optional[List[str]],
```

2022-10-13 18:01 UTC, QXgu commented on filecopy/tests/services/approval/test_client.py
> -    def test_get_approval_entities_returns_instance_of_approval_entities(self, approval_service_client, fake):
Add the new test case

2022-10-13 18:02 UTC, QXgu commented
@vmoshynskyi All the changes are up. Please check

2022-10-14 12:15 UTC, vmoshynskyi approved these changes
👍

2022-10-14 12:21 UTC, merged